server:
  port: 80

spring:
  application:
    name: cloud-payment-com.test.springcloud.service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdemo?useTimezone=true&serverTimezone=UTC
    username: root
    password: 61376554
