version: '3'
services:
  eureka-server1:
    image: spring-eureka-discovery:1.0
    container_name: cloud_eureka_1
    hostname: eureka7001.com
    ports:
      - "7001:7001"
    environment:
      - spring.profiles.active=peer1
    networks:
      - cloudnetwork

  eureka-server2:
    image: spring-eureka-discovery:1.0
    container_name: cloud_eureka_2
    hostname: eureka7002.com
    ports:
      - "7002:7002"
    environment:
      - spring.profiles.active=peer2
    networks:
      - cloudnetwork

  cloud-provider1:
    image: cloud-provider:1.0
    container_name: cloud_provider_1
    hostname: cloud-payment-service
    ports:
      - "8001:8001"
    networks:
      - cloudnetwork
      
  cloud-consumer-openfeign1:
    image: cloud-consumer-openfeign:1.0
    container_name: cloud_consumer_openfeign_1
    hostname: cloud-consumer-openfeign
    ports:
      - "80:80"
    networks:
      - cloudnetwork

networks:
  cloudnetwork:
    driver: bridge