server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/springdemo?useTimezone=true&serverTimezone=UTC
    # when using docker-compose create the provider service, the sql container that want connect need to be same network with this provider,
    # remember to use the container port instead of host port, because the sql and provider service in the same network, they can ping each other directly
    url: jdbc:mysql://sql_container3:3306/springdemo
    username: root
    password: 61376554
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # To auto generate and created the table into the database without we created
    generate-ddl: true
    hibernate:
      ddl-auto=create:

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      #单机版
      #defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: payment8001 #show in eureka server status name
    prefer-ip-address: true #can show ip address
    #Eureka client send to server heartbeats is default interval is 30seconds, now change to below
    lease-renewal-interval-in-seconds: 1
    #Eureka server received last heartbeat time limit, default is 90 seconds, overtime will remove service
    lease-expiration-duration-in-seconds: 2


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.test.springcloud.entities

