server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #路由的id,没有规定规则但要求唯一,建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #lb:// 代表从注册中心获取/lb官网说明是Ribbon负载均衡， 同时也有load balancer
          predicates:
            - Path=/payment/get/** #断言,路径相匹配的进行路由

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
            - After=2021-01-23T17:06:10.401+08:00[Asia/Singapore]
            #- Cookie=username, zzyy #可以用curl 直接在cmd测试， curl http:localhost:xxx/xxx/xx --cookie "username=zzyy"
            #- Header=X-Request-Id,\d+ #请求头要有 X-Request-Id属性并且值为整数的正则表达式
            #- Method=GET
#配了gateway, 可以直接http://localhost:9257/xxx/xxx 访问如同上面 uri http://localhost:8001/xxx/xxx, 也有负载均衡

eureka:
  isntance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka