server:
  port: 80

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: false
    service-url:
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      #单机版
      #defaultZone: http://localhost:7001/eureka/

feign:
 hystrix:
   enabled: true #课程视频中加了这个，可是一直fallback在没有micro service超时的情况,不加才正常

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMiliseconds.time: #3500 #hystrix command超时是default 1000/秒， 所以加了上面 enabled才不正常


ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的实际
  ReadTimeout: 3500
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 3500